# Site settings
title: Benjamin Roedell
twitter_username: BenjaminRoedell
name: Benjamin Roedell
location: Tampa, FL

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/benjaminroedell
 - title: GitHub
   url: https://github.com/benrobot
 - title: GitHub summary
   url: https://resume.github.io/?benrobot
 - title: StackOverflow
   url: https://stackoverflow.com/users/3166133/benrobot

intro_blurb: I am a full stack developer with experience in application security as well as unit and integration testing.

#Any buzzword skills you want to include
skills:
 - Java
 - C#
 - JavaScript
 - Gradle
 - SQL
 - Unit Testing

#Work experience is required
roles:
 - title: Awesome Developer
   start: Sep 2015
   end: Ongoing
   employer: Applicant Insight
   description: Maintain and upgrade legacy Java based systems while launching new systems using C# and .NET
 - title: Software Engineer
   start: Jan 2013
   end: Sep 2015
   employer: CAE
   description: Software Engineer for Tactical Systems on Full Flight Simulators for various military customers. Then began implementing software best practices including automated testing, static code analysis, and continuous integration.
 - title: Quality Assurance and Regulatory Affairs Manager
   start: Dec 2003
   end: Jan 2013
   employer: IsoAid
   description: Performed both software and equipment validation on critical systems

#Education is required
education:
 - level: Bachelor of Science
   date: 2012
   subject: Computer Engineering
   school: University of South Florida

#This section is optional (as is the image link below)
edx:
   profileurl: https://courses.edx.org/u/benrobot
   courses:
    - title: "CS169.1x: Software as a Service"
      link: https://s3.amazonaws.com/verify.edx.org/downloads/76cd2c64453b46ea903391c4cdd6d02a/Certificate.pdf
      date: June 16, 2014

training:
   courses:
    - title: "SANS Secure Coding in .NET: Developing Defensible Applications"
      date: April 2018
      link: https://www.sans.org/course/secure-coding-net-developing-defensible-applications
    - title: SANS Core NetWars Experience
      date: April 2018
      link: https://www.sans.org/netwars/tournament
    - title: "OWASP AppSec USA: Hands On Security in DevOps and Application Security Automation Workshop"
      date: September 2017
      link: https://appsecusa2017.sched.com/event/B26a/hands-on-security-in-devops-and-application-security-automation-workshop-1-of-2-days?iframe=no&w=100%&sidebar=no&bg=no

#List of interesting Github repo/projects to include - optional
#github:
# - benrobot/EyesOnMars

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/3166133/benrobot
   flairimageurl: https://stackoverflow.com/users/flair/3166133.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>TDD</strong>: I am proponent of Test Driven Development. I have written tests in Java, C#, C++ Python, Ruby, JavaScript, and even Powershell and SQL. I developed and performed training in automated testing for over 100 developers.<br/><br/>
   <strong>Application Security</strong>: In addition to fixing various common sense vulnerabilities (like unauthenticated access and SQL injection) I have begun applying skills learned at various security related training courses.<br/><br/>
