# Site settings
title: Benjamin Roedell
twitter_username: BenjaminRoedell
name: Benjamin Roedell
location: Tampa, FL

# Build settings
markdown: kramdown

# Google analytics tracking id (optional)
ga_tracking_id: UA-118349925-1

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/benjaminroedell
 - title: GitHub
   url: https://github.com/benrobot
 - title: GitHub summary
   url: https://resume.github.io/?benrobot
 - title: StackOverflow
   url: https://stackoverflow.com/users/3166133/benrobot

