# Site settings
title: Benjamin Roedell
twitter_username: BenjaminRoedell
name: Benjamin Roedell
location: Tampa, FL

# Build settings
markdown: kramdown

# Google analytics tracking id (optional)
ga_tracking_id: UA-118349925-1

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/benjaminroedell
 - title: GitHub
   url: https://github.com/benrobot
 - title: GitHub summary
   url: https://resume.github.io/?benrobot
 - title: StackOverflow
   url: https://stackoverflow.com/users/3166133/benrobot

intro_blurb: I am a software architect and full stack developer with experience in application security as well as unit and integration testing. My wide range of skills with languages and tools allows for innovative solutions to new problems.

#Any buzzword skills you want to include
skills:
 - Java
 - C#
 - JavaScript
 - Gradle
 - Groovy
 - Chef
 - Unit Testing
 - XUnit
 - Powershell
 - Pester
 - Ruby
 - JUnit4
 - JUnit5
 - FitNesse
 - Google Test
 - Apex
 - VisualForce
 - PdfBox
 - CometD
 - C++
 - Ada
 - Lua
 - VBA
 - SQL

#Work experience is required
roles:
 - title: <span title="Awesome Software Developer">Senior Software Developer</span>
   start: Sep 2015
   end: Present
   employer: Applicant Insight / NoMoreForms, New Port Richey, FL
   employer_description: Background Investigation and Applicant Processing
   description: 
    - Maintain and upgrade legacy Java based systems while launching new systems using .NET (C#, XUnit)
    - Integrated credit card / ACH payment system to allow applicants to pre-pay client specified fees (Java, C#)
    - Created rule based system for automated appointment of insurance agents (C#)
    - Implement unit testing for SQL functions
    - Scripted application deployment using TDD (Powershell, Pester)
    - Improve Java coding practices by implementing custom logging, unit testing, and static code analysis (slf4j, junit4, junit5, ErrorProne, SonarQube)
    - Created Gradle build scripts for legacy Java applications with custom tasks for local deployment, build versions, and packaging (Java, Gradle, Groovy)
 - title: Software Architect
   start: Jul 2015
   end: Mar 2018
   employer: Qualityze Inc., Tampa, FL
   employer_description: Qualityze Systems for Regulated Industries
   description: 
    - Build Qualityze Management System as Salesforce managed package using custom VisualForce pages (Apex, VisualForce)
    - Implement PDF manipulation using Java running on Heroku uploading to various salesforce orgs (Java, PdfBox, Apex, cometD)
    - Create method to perform VisualForce injection to increase flexibility of Salesforce managed package (VisualForce)
    - Diagnose slow pages in Salesforce and design method to reduce load time
    - Design and implement deployment process accounting for lack of source control and automation in Salesforce
 - title: Software Engineer
   start: Jan 2013
   end: Sep 2015
   employer: CAE USA Inc, Tampa, FL
   employer_description: Military Training Simulation with Active Security Clearance
   description: 
    - Enhanced Ant Contrib cpptasks to generate Visual Studio .sln file and desired .vcproj version to enable source code analysis (Java)
    - Deployed and maintained central build automation within secured IT environment (Opscode Chef)
    - Implemented wrapper over single Magnetic Variation model for multiple languages (Ada, C, C++)
    - Created Visual Studio solution wizard to streamline adoption of software best practices (JavaScript)
    - Supported multiple projects simultaneously; not the norm for recent hires (C++, C, Ada with Linux)
    - Wrote Wireshark dissector for network communication with USMC Tactical Environment (Lua)
    - Identified and implemented a database to combine multiple lists of software assets (SQL, VBA) and later converted database access to MS SQL and ASP.NET MVC (C# Razor, T-SQL)
    - Participated in numerous Kaizen workshops focusing on subjects ranging from software development best practices to identifying tools for saving money
    - Coordinated and presented training for software engineers on Automated Testing, Static Code Analysis, and Software Product Lines (Fitnesse, GoogleTest)
    - Developed tool converting Ant XML build instructions to Visual Studio format (C++)
    - Team lead for deployment and institutionalizing internally developed Software Production Line tool
 - title: Quality Assurance and Regulatory Affairs Manager
   start: Dec 2003
   end: Jan 2013
   employer: IsoAid, LLC, Port Richey, FL
   employer_description: Medical Device Manufacturer
   description: 
    - Research solutions for validation, auditing, documentation and manufacturing improvements
    - Compare and purchase equipment for sterilization, validation, sterile sealing, and automation
    - Maintained and upgraded multiple companywide databases from MS Access to MS SQL Server
    - Performed both software and equipment validation on critical systems
    - Developed and executed validation protocol for electronic signatures
    - Managed simultaneous deadlines for regulatory and quality goals
    - Upgraded Quality Assurance System to allow paperless availability
    - Submitted and received 510(k) submissions to the FDA
    - Submitted and received medical license applications to Health Canada and EU notified body
    - Created and executed sterilization validation protocols for both Ethylene Oxide and Steam sterilizers

#Education is required
education:
 - level: Bachelor of Science
   date: 2012
   subject: Computer Engineering
   school: University of South Florida

#This section is optional (as is the image link below)
edx:
   profileurl: https://courses.edx.org/u/benrobot
   courses:
    - title: "CS169.1x: Software as a Service (Ruby)"
      link: https://s3.amazonaws.com/verify.edx.org/downloads/76cd2c64453b46ea903391c4cdd6d02a/Certificate.pdf
      date: June 16, 2014

training:
   courses:
    - title: "DEV544: SANS Secure Coding in .NET: Developing Defensible Applications"
      date: April 2018
      link: https://www.sans.org/course/secure-coding-net-developing-defensible-applications
    - title: SANS Core NetWars Experience
      date: April 2018
      link: https://www.sans.org/netwars/tournament
    - title: "OWASP AppSec USA: Hands On Security in DevOps and Application Security Automation Workshop"
      date: September 2017
      link: https://appsecusa2017.sched.com/event/B26a/hands-on-security-in-devops-and-application-security-automation-workshop-1-of-2-days?iframe=no&w=100%&sidebar=no&bg=no
    - title: "Software Verification & Validation Strategies (by Noblitt and Rueland)"
    - title: "ISO 14971:2007 Medical devices -- Application of risk management to medical devices"
    - title: "ISO 13485:2003 Medical devices -- Quality management systems -- Requirements for regulatory purposes"

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/3166133/benrobot
   flairimageurl: https://stackoverflow.com/users/flair/3166133.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>TDD</strong>: I am proponent of Test Driven Development. I have written tests in Java, C#, C++ Python, Ruby, JavaScript, and even Powershell and SQL. I developed and performed training in automated testing for over 100 developers.<br/><br/>
   <strong>Application Security</strong>: In addition to fixing various common sense vulnerabilities (like unauthenticated access and SQL injection) I have begun applying skills learned at various security related training courses.<br/><br/>
